import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Hello DevOps</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://www.docker.com/">Docker</a>
        </h1>

        <p className={styles.description}>
          Hello
          <code className={styles.code}>DevOps</code>
        </p>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://swiftlet.co.th/"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <b>Puttipong Wongrak</b>
          </span>
        </a>
      </footer>
    </div>
  )
}
